#cloud-config
packages:
  - nfs-kernel-server

runcmd:
  # NFS data
  - mkdir -p /DATA
  - echo "192.168.73.25:/DATA      /DATA      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # NFS
  - echo "/shared `hostname -I | awk '{print $1}' | grep -Po '(\d+\.){3}'`0/24(rw,sync,no_root_squash,no_all_squash)" > /etc/exports
  - mkdir -p /shared
  - chown ${admin_user} /shared
  - systemctl enable nfs-kernel-server
  - systemctl restart nfs-kernel-server
  # Kubeadm  
  - echo "SUDO_UID=${admin_user} sudo -E /tmp/kubeadm-bootstrap/init-master.bash" >> /tmp/install.sh
  - su ${admin_user} -c "/tmp/install.sh"
  - kubeadm token create --print-join-command > /shared/kubeadm-join.bash
  - kubectl label nodes `hostname` type=production  
  # k8s commands
  - cat /tmp/kubeadm-bootstrap/.bashrc >> /home/ubuntu/.bashrc
  # ssh config for nodes
  # make sure that k8s node is ready, and enable easy ssh
  - su ${admin_user} -c "touch /home/ubuntu/.ssh/config"
  - mv /tmp/kubeadm-bootstrap/add_nodes.bash /home/ubuntu/
  - chmod u+x /home/ubuntu/add_nodes.bash
  - su ${admin_user} -c "/home/ubuntu/add_nodes.bash ${nb_nodes}"
  # Configure docker registry
  - echo "Host registry" >> /home/ubuntu/.ssh/config;
  - echo "        HostName "${docker_registry} >> /home/ubuntu/.ssh/config;
  - echo "        User "${admin_user} >> /home/ubuntu/.ssh/config; 
  - mv /tmp/kubeadm-bootstrap/configure_docker.bash /home/ubuntu/
  - chmod u+x /home/ubuntu/configure_docker.bash
  - su ${admin_user} -c "/home/ubuntu/configure_docker.bash ${docker_registry} ${docker_id} ${docker_password}"
  # creating flag to say that master configuration finished
  - touch /shared/k8s-initialized
