packages:
  - nfs-common

runcmd:
  # NFS
  - mkdir -p /shared
  - echo "${master_ip}:/shared      /shared      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  # creating flag to say that node configuration is on the way
  - touch /shared/node-$HOSTNAME-not-initialized
  - mkdir -p /DATA
  - echo "192.168.73.25:/DATA      /DATA      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # Kubeadm  
  - echo "while [ ! -f /shared/kubeadm-join.bash ]; do sleep 1; done; sudo bash /shared/kubeadm-join.bash" >> /tmp/install.sh
  - su ${admin_user} -c "/tmp/install.sh"
  # authorizing root login
  - sudo mv /shared/authorized_keys /root/.ssh/
  # deleting flag to say that node configuration finished
  - rm /shared/node-$HOSTNAME-not-initialized
