jupyterhub:
  ingress:
    enabled: true
    hosts:
      - ${domain}
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/issuer: letsencrypt-staging
    https:
      enabled: true
      type: nginx
    config:
      # Allow POSTs of upto 64MB, for large notebook support.
      proxy-body-size: 64m
    tls:
      - secretName: ${TLS_name}-tls
        hosts:
          - ${domain}
  hub:
    baseUrl: /jupyter/
  proxy:
    service:
      type: NodePort
  singleuser:
    memory:
       guarantee: ${mem_alloc}G
    cpu:
       guarantee: ${cpu_alloc}

# BinderHub config
config:
  BinderHub:
    hub_url: https://${domain}/jupyter
    use_registry: true
    image_prefix: ${docker_id}/${domain}-

service:
  type: NodePort

storage:
  capacity: 2G

ingress:
  enabled: true
  hosts:
    - ${domain}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: letsencrypt-staging
  https:
    enabled: true
    type: nginx
  config:
    # Allow POSTs of upto 64MB, for large notebook support.
    proxy-body-size: 64m
  tls:
    - secretName: ${TLS_name}-tls
      hosts: 
        - ${domain}
